# Generated by Django 4.2.10 on 2024-03-12 17:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="date_posted",
            new_name="posted_date",
        ),
    ]
