CREATE DATABASE OOS CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE OOS;
CREATE TABLE orders (
    id SERIAL PRIMARY KEY,
    items VARCHAR(20),
    amount VARCHAR(20),
    note VARCHAR(20),
    urgent VARCHAR(20),
    is_deleted INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE USER OOS IDENTIFIED WITH mysql_native_password BY '123456';
GRANT ALL PRIVILEGES ON OOS.* TO OOS;